"""feat: enhance lms models with advanced features

Revision ID: d7094ffdcb56
Revises: a1b2c3d4e5f6
Create Date: 2026-03-22 20:22:04.281894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7094ffdcb56'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types manually to avoid Postgres errors
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enrollmentsource') THEN CREATE TYPE enrollmentsource AS ENUM ('self', 'admin', 'group'); END IF; END $$;")

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('certificate_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('html_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_templates_id'), 'certificate_templates', ['id'], unique=False)
    op.create_table('course_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_user_rating')
    )
    op.create_index(op.f('ix_course_ratings_id'), 'course_ratings', ['id'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('total_time_sec', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_user_leaderboard')
    )
    op.create_index(op.f('ix_leaderboard_entries_id'), 'leaderboard_entries', ['id'], unique=False)
    op.create_table('coding_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_limit_ms', sa.Integer(), nullable=True),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    op.create_index(op.f('ix_coding_exercises_id'), 'coding_exercises', ['id'], unique=False)
    op.create_table('lesson_discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['lesson_discussions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_discussions_id'), 'lesson_discussions', ['id'], unique=False)
    op.create_table('ppt_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('slide_no', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppt_slides_id'), 'ppt_slides', ['id'], unique=False)
    op.create_table('code_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['coding_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_id'), 'code_submissions', ['id'], unique=False)
    op.create_table('interactive_video_markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('marker_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp_sec', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('quiz_question_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactive_video_markers_id'), 'interactive_video_markers', ['id'], unique=False)
    op.create_table('matching_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(length=500), nullable=True),
    sa.Column('target_text', sa.String(length=500), nullable=True),
    sa.Column('source_image_id', sa.Integer(), nullable=True),
    sa.Column('target_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_image_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['target_image_id'], ['media_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_pairs_id'), 'matching_pairs', ['id'], unique=False)
    op.drop_index('ix_course_progress_course_id', table_name='course_progress')
    op.drop_index('ix_course_progress_user_id', table_name='course_progress')
    op.add_column('courses', sa.Column('expiry_days', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('require_sequential', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('passing_score', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('rating_avg', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.drop_index('ix_courses_instructor_id', table_name='courses')
    op.drop_index('ix_courses_is_featured', table_name='courses')
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_index('ix_courses_status_category', table_name='courses')
    op.add_column('enrollments', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrollments', sa.Column('source', postgresql.ENUM('self', 'admin', 'group', name='enrollmentsource'), server_default='self', nullable=False))
    op.add_column('enrollments', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_index('ix_enrollments_course_id', table_name='enrollments')
    op.drop_index('ix_enrollments_status', table_name='enrollments')
    op.drop_index('ix_enrollments_user_course', table_name='enrollments')
    op.drop_index('ix_enrollments_user_id', table_name='enrollments')
    op.create_foreign_key(None, 'enrollments', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.add_column('lesson_progress', sa.Column('video_position_seconds', sa.Integer(), nullable=True))
    op.drop_index('ix_lesson_progress_lesson_id', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_user_id', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_user_lesson', table_name='lesson_progress')
    op.drop_index('ix_lessons_content_type', table_name='lessons')
    op.drop_index('ix_lessons_media_file_id', table_name='lessons')
    op.drop_index('ix_lessons_module_id', table_name='lessons')
    op.drop_index('ix_lessons_module_preview', table_name='lessons')
    op.drop_index('ix_media_files_media_type', table_name='media_files')
    op.drop_index('ix_media_files_status', table_name='media_files')
    op.drop_index('ix_media_files_type_status', table_name='media_files')
    op.drop_index('ix_media_files_uploaded_by', table_name='media_files')
    op.drop_index('ix_modules_course_id', table_name='modules')
    op.drop_index('ix_modules_order', table_name='modules')
    op.add_column('quiz_attempts', sa.Column('time_taken_seconds', sa.Integer(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('result_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quiz_questions', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('quiz_questions', sa.Column('shuffle_options', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'quiz_questions', 'media_files', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_column('quiz_questions', 'shuffle_options')
    op.drop_column('quiz_questions', 'image_id')
    op.drop_column('quiz_attempts', 'result_detail')
    op.drop_column('quiz_attempts', 'time_taken_seconds')
    op.create_index('ix_modules_order', 'modules', ['order'], unique=False)
    op.create_index('ix_modules_course_id', 'modules', ['course_id'], unique=False)
    op.create_index('ix_media_files_uploaded_by', 'media_files', ['uploaded_by'], unique=False)
    op.create_index('ix_media_files_type_status', 'media_files', ['media_type', 'status'], unique=False)
    op.create_index('ix_media_files_status', 'media_files', ['status'], unique=False)
    op.create_index('ix_media_files_media_type', 'media_files', ['media_type'], unique=False)
    op.create_index('ix_lessons_module_preview', 'lessons', ['module_id', 'is_free_preview'], unique=False)
    op.create_index('ix_lessons_module_id', 'lessons', ['module_id'], unique=False)
    op.create_index('ix_lessons_media_file_id', 'lessons', ['media_file_id'], unique=False)
    op.create_index('ix_lessons_content_type', 'lessons', ['content_type'], unique=False)
    op.create_index('ix_lesson_progress_user_lesson', 'lesson_progress', ['user_id', 'lesson_id'], unique=True)
    op.create_index('ix_lesson_progress_user_id', 'lesson_progress', ['user_id'], unique=False)
    op.create_index('ix_lesson_progress_lesson_id', 'lesson_progress', ['lesson_id'], unique=False)
    op.drop_column('lesson_progress', 'video_position_seconds')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_index('ix_enrollments_user_id', 'enrollments', ['user_id'], unique=False)
    op.create_index('ix_enrollments_user_course', 'enrollments', ['user_id', 'course_id'], unique=True)
    op.create_index('ix_enrollments_status', 'enrollments', ['status'], unique=False)
    op.create_index('ix_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.drop_column('enrollments', 'group_id')
    op.drop_column('enrollments', 'source')
    op.drop_column('enrollments', 'expiry_date')
    op.create_index('ix_courses_status_category', 'courses', ['status', 'category'], unique=False)
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    op.create_index('ix_courses_is_featured', 'courses', ['is_featured'], unique=False)
    op.create_index('ix_courses_instructor_id', 'courses', ['instructor_id'], unique=False)
    op.drop_column('courses', 'rating_count')
    op.drop_column('courses', 'rating_avg')
    op.drop_column('courses', 'passing_score')
    op.drop_column('courses', 'require_sequential')
    op.drop_column('courses', 'expiry_days')
    op.create_index('ix_course_progress_user_id', 'course_progress', ['user_id'], unique=False)
    op.create_index('ix_course_progress_course_id', 'course_progress', ['course_id'], unique=False)
    op.drop_index(op.f('ix_matching_pairs_id'), table_name='matching_pairs')
    op.drop_table('matching_pairs')
    op.drop_index(op.f('ix_interactive_video_markers_id'), table_name='interactive_video_markers')
    op.drop_table('interactive_video_markers')
    op.drop_index(op.f('ix_code_submissions_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    op.drop_index(op.f('ix_ppt_slides_id'), table_name='ppt_slides')
    op.drop_table('ppt_slides')
    op.drop_index(op.f('ix_lesson_discussions_id'), table_name='lesson_discussions')
    op.drop_table('lesson_discussions')
    op.drop_index(op.f('ix_coding_exercises_id'), table_name='coding_exercises')
    op.drop_table('coding_exercises')
    op.drop_index(op.f('ix_leaderboard_entries_id'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_course_ratings_id'), table_name='course_ratings')
    op.drop_table('course_ratings')
    op.drop_index(op.f('ix_certificate_templates_id'), table_name='certificate_templates')
    op.drop_table('certificate_templates')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
